# Generated by Django 5.0.4 on 2024-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='amount',
            new_name='sentAmount',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='currency',
            new_name='sentCurrency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='sentAmount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency',
            new_name='sentCurrency',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiveAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiveCurrency',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiveAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiveCurrency',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
